apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x78g09psc-nodejs-gitops
  description: This is GitOps manifest for x78g09psc-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=x78g09psc-nodejs
    backstage.io/kubernetes-id: x78g09psc-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: x78g09psc-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x78g09psc-nodejs
